---
sidebar: sidebar 
permalink: users.assigntoappgroup.html 
summary: VDM のアプリケーショングループにユーザーを割り当てる 
keywords:  
---
= アプリケーショングループへのユーザーの割り当て
:toc: macro
:hardbreaks:
:toclevels: 2
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:keywords: 
:toc-position: content




== ユーザー割り当て方法

ユーザーは、 AD セキュリティグループを介してセッションホスト仮想マシン（ SHVM ）に割り当てられます。

ホストプールごとに、ワークスペース内の [ ユーザーとグループ ] タブにリンクされたユーザーグループがあります。

ユーザーグループには、ワークスペース ID （各ワークスペースに固有の 3 ～ 4 桁の数字コード）とホストプールの名前が付けられます。

たとえば、グループ「 jzsx Shared Users 」は VDM の Shared Users ホストプールにリンクされています。"jzsx Shared Users" に追加されたすべてのユーザーには、 " 共有ユーザー " ホストプール内のセッションホストへのアクセス権が割り当てられます。

.をクリックして、ホストプールにユーザを割り当てます
. ワークスペース内の「ユーザーとグループ」に移動します
. ユーザをグループに追加するには、グループ内のユーザリストを編集します。
. 自動化では、ユーザグループのメンバーが自動的に同期され、ユーザに適切なホストプール、アプリケーショングループ、およびアプリケーションへのアクセスが許可されます。



NOTE: ユーザーは、 1 つの（ 1 つだけの）アプリグループにのみ割り当てる必要があります。ホストプールのタイプ（共有、 VDI 、または GPU ）は、 VDM 用に購入したライセンス済み SKU と一致している必要があります。複数のアプリケーショングループに対してユーザや割り当てが正しくないと、原因リソースの競合の問題が発生し、環境内で作業している同僚に影響が及ぶ可能性があります。
